# Generated by Django 3.2.7 on 2021-09-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
